package com.chinasei.hibernate;



/**
 * Users generated by MyEclipse - Hibernate Tools
 */

public class Users  implements java.io.Serializable {


    // Fields    

     private String id;
     private String userName;
     private String password;
     private String email;


    // Constructors

    /** default constructor */
    public Users() {
    }

	/** minimal constructor */
    public Users(String id, String userName, String password) {
        this.id = id;
        this.userName = userName;
        this.password = password;
    }
    
    /** full constructor */
    public Users(String id, String userName, String password, String email) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.email = email;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
   


}